// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-prices.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_prices_default = defineTool({
  name: "list_prices",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u0446\u0435\u043D \u043D\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0430\u043A\u0442\u0443\u0430\u043B\u044C\u043D\u044B\u0435 \u0446\u0435\u043D\u044B \u043D\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440 \u043F\u043E \u0432\u0441\u0435\u043C \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F\u043C \u0422\u0421 (\u0438\u043B\u0438 \u043F\u043E \u043E\u0434\u043D\u043E\u0439 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u0438, \u0435\u0441\u043B\u0438 \u0443\u043A\u0430\u0437\u0430\u043D category_code, \u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440 M1, N1, L).",
  inputSchema: {
    category_code: z.string().trim().min(1).max(10).optional().describe("\u041E\u043F\u0446\u0438\u043E\u043D\u0430\u043B\u044C\u043D\u044B\u0439 \u043A\u043E\u0434 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u0438 \u0422\u0421, \u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440: L, M1, M2, M3, N1, N2, N3, O1, O2, O3, O4.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_code }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("prices").select("category_code, category_name, description, details, price_rub, updated_at").order("category_code");
    if (category_code) query = query.eq("category_code", category_code.toUpperCase());
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-seo-locations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_seo_locations_default = defineTool2({
  name: "list_seo_locations",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A SEO-\u0441\u0442\u0440\u0430\u043D\u0438\u0446 (\u0440\u0430\u0439\u043E\u043D\u044B \u0438 \u0443\u0441\u043B\u0443\u0433\u0438)",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u044B\u0435 SEO-\u0441\u0442\u0440\u0430\u043D\u0438\u0446\u044B \u0441\u0430\u0439\u0442\u0430: \u0440\u0430\u0439\u043E\u043D\u044B \u0411\u0440\u044F\u043D\u0441\u043A\u0430 \u0438 \u0442\u0435\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0435 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u044B (\u0446\u0435\u043D\u044B, \u0434\u0438\u0430\u0433\u043D\u043E\u0441\u0442\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043A\u0430\u0440\u0442\u0430, \u0434\u043B\u044F \u041E\u0421\u0410\u0413\u041E \u0438 \u0442.\u0434.) \u0441 \u0438\u0445 slug, \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0430\u043C\u0438 \u0438 \u043F\u0443\u0442\u044F\u043C\u0438.",
  inputSchema: {
    page_type: z2.string().trim().min(1).max(50).optional().describe("\u041E\u043F\u0446\u0438\u043E\u043D\u0430\u043B\u044C\u043D\u044B\u0439 \u0444\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0442\u0438\u043F\u0443 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u044B, \u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440: district, service.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ page_type }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("seo_locations").select("slug, location_name, page_type, h1, seo_title, seo_description, route_path, sort_order").eq("is_active", true).order("sort_order");
    if (page_type) query = query.eq("page_type", page_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { locations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-inspection-request.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_inspection_request_default = defineTool3({
  name: "create_inspection_request",
  title: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0437\u0430\u044F\u0432\u043A\u0443 \u043D\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440",
  description: "\u0421\u043E\u0437\u0434\u0430\u0451\u0442 \u0437\u0430\u044F\u0432\u043A\u0443 \u043A\u043B\u0438\u0435\u043D\u0442\u0430 \u043D\u0430 \u043F\u0440\u043E\u0445\u043E\u0436\u0434\u0435\u043D\u0438\u0435 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440\u0430. \u041E\u043F\u0435\u0440\u0430\u0442\u043E\u0440 \u043F\u0435\u0440\u0435\u0437\u0432\u043E\u043D\u0438\u0442 \u043F\u043E \u0443\u043A\u0430\u0437\u0430\u043D\u043D\u043E\u043C\u0443 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\u0443 \u0434\u043B\u044F \u043F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043D\u0438\u044F \u0434\u0430\u0442\u044B \u0438 \u0432\u0440\u0435\u043C\u0435\u043D\u0438.",
  inputSchema: {
    name: z3.string().trim().min(1).max(100).describe("\u0418\u043C\u044F \u043A\u043B\u0438\u0435\u043D\u0442\u0430."),
    phone: z3.string().trim().min(5).max(20).describe("\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u043D\u044B\u0439 \u0442\u0435\u043B\u0435\u0444\u043E\u043D \u043A\u043B\u0438\u0435\u043D\u0442\u0430."),
    vehicle_category: z3.string().trim().min(1).max(10).optional().describe("\u041A\u043E\u0434 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u0438 \u0422\u0421: L, M1, M2, M3, N1, N2, N3, O1, O2, O3, O4."),
    plate_number: z3.string().trim().max(15).optional().describe("\u0413\u043E\u0441\u043D\u043E\u043C\u0435\u0440 \u0430\u0432\u0442\u043E\u043C\u043E\u0431\u0438\u043B\u044F."),
    desired_date: z3.string().trim().max(20).optional().describe("\u0416\u0435\u043B\u0430\u0435\u043C\u0430\u044F \u0434\u0430\u0442\u0430 \u0432 \u0444\u043E\u0440\u043C\u0430\u0442\u0435 YYYY-MM-DD."),
    comment: z3.string().trim().max(500).optional().describe("\u0414\u043E\u043F\u043E\u043B\u043D\u0438\u0442\u0435\u043B\u044C\u043D\u044B\u0439 \u043A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0439.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, phone, vehicle_category, plate_number, desired_date, comment }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const payload = {
      source_form: "mcp",
      name,
      phone,
      vehicle_category: vehicle_category ? vehicle_category.toUpperCase() : null,
      plate_number: plate_number ?? null,
      desired_date: desired_date ?? null,
      comment: comment ?? null
    };
    const { data, error } = await supabase.from("requests").insert(payload).select("id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    try {
      await supabase.functions.invoke("send-notification", { body: payload });
    } catch (_) {
    }
    return {
      content: [{ type: "text", text: `\u0417\u0430\u044F\u0432\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0430. ID: ${data.id}. \u041C\u044B \u0441\u0432\u044F\u0436\u0435\u043C\u0441\u044F \u0441 \u043A\u043B\u0438\u0435\u043D\u0442\u043E\u043C \u043F\u043E \u0442\u0435\u043B\u0435\u0444\u043E\u043D\u0443 ${phone}.` }],
      structuredContent: { id: data.id, created_at: data.created_at }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B \u0438 \u0433\u0440\u0430\u0444\u0438\u043A \u0440\u0430\u0431\u043E\u0442\u044B \u043F\u0443\u043D\u043A\u0442\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440\u0430",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0430\u0434\u0440\u0435\u0441, \u0442\u0435\u043B\u0435\u0444\u043E\u043D, email \u0438 \u0433\u0440\u0430\u0444\u0438\u043A \u0440\u0430\u0431\u043E\u0442\u044B \u043F\u0443\u043D\u043A\u0442\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0432 \u0411\u0440\u044F\u043D\u0441\u043A\u0435.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "\u041F\u0443\u043D\u043A\u0442 \u0442\u0435\u0445\u043D\u0438\u0447\u0435\u0441\u043A\u043E\u0433\u043E \u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u2014 \u0411\u0440\u044F\u043D\u0441\u043A",
            city: "\u0411\u0440\u044F\u043D\u0441\u043A",
            address: "\u0433. \u0411\u0440\u044F\u043D\u0441\u043A (\u0443\u0442\u043E\u0447\u043D\u044F\u0439\u0442\u0435 \u043F\u043E \u0442\u0435\u043B\u0435\u0444\u043E\u043D\u0443)",
            phone: "+7 (\u0441\u043E\u043E\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430\u043C \u043D\u0430 \u0441\u0430\u0439\u0442\u0435)",
            website: "https://bryansk-auto-inspect.lovable.app",
            hours: {
              mon_fri: "09:00\u201318:00",
              sat: "09:00\u201315:00",
              sun: "\u0432\u044B\u0445\u043E\u0434\u043D\u043E\u0439"
            },
            services: "\u0422\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440 \u0432\u0441\u0435\u0445 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u0439 \u0422\u0421 (L, M1, M2, M3, N1\u2013N3, O1\u2013O4), \u0434\u0438\u0430\u0433\u043D\u043E\u0441\u0442\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043A\u0430\u0440\u0442\u0430 \u0434\u043B\u044F \u041E\u0421\u0410\u0413\u041E.",
            duration_minutes: "15\u201330"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bryansk-tehosmotr-mcp",
  title: "\u0422\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440 \u0411\u0440\u044F\u043D\u0441\u043A \u2014 MCP",
  version: "0.1.0",
  instructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B \u043F\u0443\u043D\u043A\u0442\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0432 \u0411\u0440\u044F\u043D\u0441\u043A\u0435: \u043F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0430\u043A\u0442\u0443\u0430\u043B\u044C\u043D\u044B\u0435 \u0446\u0435\u043D\u044B (list_prices), \u0441\u043F\u0438\u0441\u043E\u043A \u0440\u0430\u0439\u043E\u043D\u043E\u0432 \u0438 SEO-\u0441\u0442\u0440\u0430\u043D\u0438\u0446 (list_seo_locations), \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u044B \u0438 \u0433\u0440\u0430\u0444\u0438\u043A \u0440\u0430\u0431\u043E\u0442\u044B (get_contact_info), \u0441\u043E\u0437\u0434\u0430\u0442\u044C \u0437\u0430\u044F\u0432\u043A\u0443 \u043D\u0430 \u0442\u0435\u0445\u043E\u0441\u043C\u043E\u0442\u0440 \u043E\u0442 \u043A\u043B\u0438\u0435\u043D\u0442\u0430 (create_inspection_request).",
  tools: [list_prices_default, list_seo_locations_default, get_contact_info_default, create_inspection_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
